# Generated by Django 4.2 on 2023-04-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='project',
            name='precio',
            field=models.CharField(default='0.00', max_length=170),
        ),
    ]
