# Generated by Django 4.2 on 2023-04-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_description_project_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nombre',
            new_name='nombre_producto',
        ),
    ]
