# Generated by Django 4.2 on 2023-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_nombre_project_nombre_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nombre_producto',
            new_name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='project',
            name='producto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
